import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { parseTokenList } from './auth.ts';
import { createSqliteStore } from './store.ts';
import type { Store } from './types.ts';

export type LiteLLMConfigOptions = {
  publicModels?: string[];
  upstreamModel?: string;
  masterKey?: string;
  requestTimeoutSeconds?: number;
  fallbackAliases?: number;
  additionalDropParams?: string[];
};

const defaultPublicModels = [
  'mimo-v2.5-pro',
  'gpt-5.4',
  'gpt-5',
  'gpt-5-mini',
  'gpt-5.1',
  'gpt-4.1',
  'codex-auto-review',
  'codex-mini-latest',
  'codex-latest'
];

const defaultAdditionalDropParams = [
  'store',
  'background',
  'include',
  'metadata',
  'reasoning',
  'truncation',
  'text',
  'top_logprobs',
  'parallel_tool_calls',
  'tool_choice.type',
  'tools[*].strict',
  'tools[*].annotations',
  'tools[*].metadata'
];

export async function buildLiteLLMConfig(store: Store, options: LiteLLMConfigOptions = {}): Promise<string> {
  const publicModels = normalizeList(options.publicModels ?? parseCsv(process.env.LITELLM_PUBLIC_MODELS) ?? defaultPublicModels);
  const upstreamModel = options.upstreamModel ?? process.env.LITELLM_UPSTREAM_MODEL ?? 'mimo-v2.5-pro';
  const masterKey = options.masterKey ?? parseTokenList(process.env.PROXY_TOKENS, 'change-me-proxy')[0];
  const requestTimeoutSeconds = options.requestTimeoutSeconds ?? Math.ceil(Number(process.env.UPSTREAM_TIMEOUT_MS ?? 120000) / 1000);
  const fallbackAliases = options.fallbackAliases ?? Number(process.env.LITELLM_FALLBACK_ALIASES ?? 3);
  const additionalDropParams = normalizeList(options.additionalDropParams ?? parseCsv(process.env.LITELLM_ADDITIONAL_DROP_PARAMS) ?? defaultAdditionalDropParams);
  const rows = (await store.listActiveKeysForRouting())
    .filter((row) => row.groupEnabled && row.status === 'active')
    .sort((a, b) => a.groupSortOrder - b.groupSortOrder || a.sortOrder - b.sortOrder || a.id - b.id);
  const aliasCount = Math.max(0, Math.min(rows.length - 1, Number.isFinite(fallbackAliases) ? fallbackAliases : 0));

  const lines: string[] = [
    '# Generated by mimo-pool. Do not commit this file; it contains raw API keys.',
    'model_list:'
  ];

  if (rows.length === 0) {
    lines.push('  []');
  } else {
    for (const publicModel of publicModels) {
      rows.forEach((row) => {
        lines.push(...modelEntry({
          modelName: publicModel,
          upstreamModel,
          apiBase: row.openaiBaseUrl,
          apiKey: row.apiKey,
          requestTimeoutSeconds,
          additionalDropParams
        }));
      });
      for (let aliasIndex = 1; aliasIndex <= aliasCount; aliasIndex += 1) {
        rows.slice(aliasIndex).forEach((row) => {
          lines.push(...modelEntry({
            modelName: fallbackModelName(publicModel, aliasIndex),
            upstreamModel,
            apiBase: row.openaiBaseUrl,
            apiKey: row.apiKey,
            requestTimeoutSeconds,
            additionalDropParams
          }));
        });
      }
    }
  }

  lines.push('router_settings:');
  if (aliasCount === 0) {
    lines.push('  fallbacks: []');
  } else {
    lines.push('  fallbacks:');
    for (const publicModel of publicModels) {
      const fallbackNames = Array.from({ length: aliasCount }, (_value, index) => fallbackModelName(publicModel, index + 1));
      lines.push(`    - ${yamlString(publicModel)}: [${fallbackNames.map(yamlString).join(', ')}]`);
      for (let aliasIndex = 1; aliasIndex < aliasCount; aliasIndex += 1) {
        const fallbackNamesForAlias = Array.from({ length: aliasCount - aliasIndex }, (_value, index) => fallbackModelName(publicModel, aliasIndex + index + 1));
        lines.push(`    - ${yamlString(fallbackModelName(publicModel, aliasIndex))}: [${fallbackNamesForAlias.map(yamlString).join(', ')}]`);
      }
    }
  }

  lines.push(
    'litellm_settings:',
    '  drop_params: true',
    '  num_retries: 0',
    'general_settings:',
    `  master_key: ${yamlString(masterKey)}`
  );

  return `${lines.join('\n')}\n`;
}

function modelEntry(input: { modelName: string; upstreamModel: string; apiBase: string; apiKey: string; requestTimeoutSeconds: number; additionalDropParams: string[] }): string[] {
  return [
    `  - model_name: ${yamlString(input.modelName)}`,
    '    litellm_params:',
    `      model: ${yamlString(`openai/${input.upstreamModel}`)}`,
    `      api_base: ${yamlString(input.apiBase)}`,
    `      api_key: ${yamlString(input.apiKey)}`,
    '      use_chat_completions_api: true',
    `      additional_drop_params: [${input.additionalDropParams.map(yamlString).join(', ')}]`,
    `      timeout: ${Number.isFinite(input.requestTimeoutSeconds) && input.requestTimeoutSeconds > 0 ? input.requestTimeoutSeconds : 120}`
  ];
}

function fallbackModelName(publicModel: string, index: number): string {
  return `${publicModel}__fallback_${index}`;
}

function parseCsv(value: string | undefined): string[] | undefined {
  if (!value) return undefined;
  return value.split(',').map((item) => item.trim()).filter(Boolean);
}

function normalizeList(values: string[]): string[] {
  return [...new Set(values.map((value) => value.trim()).filter(Boolean))];
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

async function main(): Promise<void> {
  const outputPath = process.env.LITELLM_CONFIG_PATH ?? 'data/litellm-config.yaml';
  const store = createSqliteStore();
  try {
    const config = await buildLiteLLMConfig(store);
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, config, 'utf8');
    console.log(`LiteLLM config written to ${outputPath}`);
  } finally {
    store.close?.();
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
